spring.application.name=Java_Web_Service_Session03_Bai5

spring.datasource.url=jdbc:mysql://localhost:3306/java_webservice_ss3_bai5?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=123456789

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.sql.init.mode=always
